# Generated by Django 2.2.12 on 2021-08-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('body', models.TextField(max_length=4000)),
            ],
        ),
    ]
